spring.application.name=scholarship-rag-backend
spring.config.import=optional:file:./.env[.properties],optional:file:./scholarship-rag-backend/.env[.properties]

groq.api.key=${GROQ_API_KEY}
groq.model.name=${GROQ_MODEL_NAME}
groq.base.url=${GROQ_BASE_URL}

gemini.api.key=${GEMINI_API_KEY}
gemini.model.name=${GEMINI_EMBEDDING_MODEL_NAME}