spring.application.name=scholarship-rag-backend

# Groq (reasoning model)
llm.groq.api-key=${GROQ_API_KEY}
llm.groq.model-name=${GROQ_MODEL_NAME}
llm.groq.base-url=${GROQ_BASE_URL}

# OpenRouter (fallback)
llm.openrouter.api-key=${OPENROUTER_API_KEY}
llm.openrouter.model-name=${OPENROUTER_MODEL_NAME}
llm.openrouter.base-url=${OPENROUTER_BASE_URL}

# Gemini (embedding model)
llm.gemini.api-key=${GEMINI_API_KEY}
llm.gemini.model-name=${GEMINI_EMBEDDING_MODEL_NAME}

# Cerebras (future implementation as fallback llm)
llm.cerebras.api-key=${CEREBRAS_API_KEY}
llm.cerebras.model-name=${CEREBRAS_MODEL_NAME}
llm.cerebras.base-url=${CEREBRAS_BASE_URL}