spring.application.name=scholarship-rag-backend
spring.config.import=optional:file:./.env[.properties],optional:file:./scholarship-rag-backend/.env[.properties]

groq.api.key=${GROQ_API_KEY}
groq.model.name=${GROQ_MODEL_NAME}
groq.base.url=${GROQ_BASE_URL}

openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.model.name=${OPENROUTER_MODEL_NAME}
openrouter.base.url=${OPENROUTER_BASE_URL}

cerebras.api.key=${CEREBRAS_API_KEY}
cerebras.model.name=${CEREBRAS_MODEL_NAME}
cerebras.base.url=${CEREBRAS_BASE_URL}

gemini.api.key=${GEMINI_API_KEY}
gemini.model.name=${GEMINI_EMBEDDING_MODEL_NAME}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
conversation.memory.ttl-hours=${REDIS_TTL_HOURS}

embedding.dimension=${EMBEDDING_DIMENSION}

retrieval.top-k=${RETRIEVAL_TOP_K}